<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>TastyWay</title>
    <meta name="keywords" content="Rutas de comida, Foodie">
    <meta name="author" content="Dayana Lizbeth">
    <meta name="copyright" content="TastyWay">
    <link rel="shortcut icon" href="image/tastyway.png" type="image/x-icon">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
        integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

    <!-- JAVASCRIPT -->
    <script type="text/javascript" src="javascript.js"></script>

</head>
<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    body {
        font-family: "Open Sans", sans-serif;
    }

    header {
        width: 100%;
        height: 200px;
        background: #43C6AC;
        /* fallback for old browsers */
        background: -webkit-linear-gradient(to right, #F8FFAE, #43C6AC);
        /* Chrome 10-25, Safari 5.1-6 */
        background: linear-gradient(to right, #F8FFAE, #43C6AC);
        /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        background-size: cover;
        background-attachment: fixed;
        position: relative;
    }

    nav {
        text-align: right;
        padding: 30px 50px 0 0;
    }

    nav>a {
        color: #fff;
        font-weight: 700;
        text-decoration: none;
        margin-right: 10px;
    }

    nav>a:hover {
        text-decoration: underline;
    }

    .wave {
        position: absolute;
        bottom: 0;
        width: 100%;
    }
</style>

<body>
    <header>
        <!-- Menú de Navegación -->
        <nav>
            <a href="index.php">Inicio</a>
            <a href="nosotros.php">Nosotros</a>
            <a href="rutas.php">Rutas</a>
            <a href="contacto.php">Contacto</a>
            <a href="usuario.php"><i class="fas fa-user"></i></a>
        </nav>

        <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->
        <div class="wave" style="height: 150px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none"
                style="height: 100%; width: 100%;">
                <path d="M-2.48,86.11 C187.69,161.89 373.36,11.31 500.00,49.85 L508.23,153.04 L0.00,149.60 Z"
                    style="stroke: none; fill: #fff;"></path>
            </svg></div>
    </header>

    <section class="menu contenedor">
        <h2 class="texto-platillos">Platillos populares</h2>
        <div class="botones-platillos">
            <button class="todos btn btn-verde">Todos</button>
            <button class="ensaladas btn btn-verde">Ensaladas</button>
            <button class="pasta btn btn-verde">Pasta</button>
            <button class="pizza btn btn-verde">Pizza</button>
            <button class="postres btn btn-verde">Postres</button>
        </div>
        <div class="platillos">
            <div class="platillo" data-platillo="ensalada">
                <img data-src="assets/img/ceviche.jpg" alt="ensalada">
                <h2>Quinoa</h2>
                <p>Quinoa, cerezas, tomate, aceitunas, cereal.</p>
                <div class="precio">
                    <p>$40.0</p>
                    <button><i class="fas fa-shopping-basket"></i></button>
                </div>
            </div>
            <div class="platillo" data-platillo="ensalada">
                <img data-src="assets/img/ensalada2.webp" alt="ensalada">
                <h2>Quinoa</h2>
                <p>Quinoa, cerezas, tomate, aceitunas, cereal.</p>
                <div class="precio">
                    <p>$40.0</p>
                    <button><i class="fas fa-shopping-basket"></i></button>
                </div>
            </div>
            <div class="platillo" data-platillo="ensalada">
                <img data-src="assets/img/ensalada2.webp" alt="ensalada">
                <h2>Quinoa</h2>
                <p>Quinoa, cerezas, tomate, aceitunas, cereal.</p>
                <div class="precio">
                    <p>$40.0</p>
                    <button><i class="fas fa-shopping-basket"></i></button>
                </div>
            </div>
            <div class="platillo" data-platillo="pasta">
                <img data-src="assets/img/pasta1.webp" alt="pasta">
                <h2>Quinoa</h2>
                <p>Quinoa, cerezas, tomate, aceitunas, cereal.</p>
                <div class="precio">
                    <p>$40.0</p>
                    <button><i class="fas fa-shopping-basket"></i></button>
                </div>
            </div>
            <div class="platillo" data-platillo="pasta">
                <img data-src="assets/img/pasta2.webp" alt="pasta">
                <h2>Quinoa</h2>
                <p>Quinoa, cerezas, tomate, aceitunas, cereal.</p>
                <div class="precio">
                    <p>$40.0</p>
                    <button><i class="fas fa-shopping-basket"></i></button>
                </div>
            </div>
            <div class="platillo" data-platillo="pasta">
                <img data-src="assets/img/pasta2.webp" alt="pasta">
                <h2>Quinoa</h2>
                <p>Quinoa, cerezas, tomate, aceitunas, cereal.</p>
                <div class="precio">
                    <p>$40.0</p>
                    <button><i class="fas fa-shopping-basket"></i></button>
                </div>
            </div>
            <div class="platillo" data-platillo="pizza">
                <img data-src="assets/img/pizza1.webp" alt="pizza">
                <h2>Quinoa</h2>
                <p>Quinoa, cerezas, tomate, aceitunas, cereal.</p>
                <div class="precio">
                    <p>$40.0</p>
                    <button><i class="fas fa-shopping-basket"></i></button>
                </div>
            </div>
            <div class="platillo" data-platillo="pizza">
                <img data-src="assets/img/pizza2.webp" alt="pizza">
                <h2>Quinoa</h2>
                <p>Quinoa, cerezas, tomate, aceitunas, cereal.</p>
                <div class="precio">
                    <p>$40.0</p>
                    <button><i class="fas fa-shopping-basket"></i></button>
                </div>
            </div>
            <div class="platillo" data-platillo="pizza">
                <img data-src="assets/img/pizza2.webp" alt="pizza">
                <h2>Quinoa</h2>
                <p>Quinoa, cerezas, tomate, aceitunas, cereal.</p>
                <div class="precio">
                    <p>$40.0</p>
                    <button><i class="fas fa-shopping-basket"></i></button>
                </div>
            </div>
            <div class="platillo" data-platillo="postre">
                <img data-src="assets/img/postres1.webp" alt="postre">
                <h2>Quinoa</h2>
                <p>Quinoa, cerezas, tomate, aceitunas, cereal.</p>
                <div class="precio">
                    <p>$40.0</p>
                    <button><i class="fas fa-shopping-basket"></i></button>
                </div>
            </div>
            <div class="platillo" data-platillo="postre">
                <img data-src="assets/img/postres2.webp" alt="postre">
                <h2>Quinoa</h2>
                <p>Quinoa, cerezas, tomate, aceitunas, cereal.</p>
                <div class="precio">
                    <p>$40.0</p>
                    <button><i class="fas fa-shopping-basket"></i></button>
                </div>
            </div>
            <div class="platillo" data-platillo="postre">
                <img data-src="assets/img/postres2.webp" alt="postre">
                <h2>Quinoa</h2>
                <p>Quinoa, cerezas, tomate, aceitunas, cereal.</p>
                <div class="precio">
                    <p>$40.0</p>
                    <button><i class="fas fa-shopping-basket"></i></button>
                </div>
            </div>
        </div>
    </section>

</body>

</html>